### ISSUE TITLE
Support for Flutter 3.0

### ISSUE THREAD

**Issue by rlee1990** [100mslive/100ms-flutter#591] opened 2022-06-01 14:16 UTC
Please add support for Flutter 3.0 and greater.

**Comment by rlee1990** [comment] 2022-07-13 01:16
@Decoder07 it appears there is an issue with this and/or flutter 3.0+ where if I have buttons with this package and its video view in a stack this will always be over top of the buttons. If I use the main branch and downgrade flutter to 2.10.5 it works as expected.

**Comment by Decoder07** [comment] 2022-07-13 06:22
@rlee1990  there are some issues in flutter 3.0+ surfaceViewRenderers and that is causing the issue.Flutter will be releasing a new version,that should fix this.

**Comment by joshmossas** [comment] 2022-08-06 20:12
If anyone here is still looking for a way around this, the fix for this is now in the latest flutter beta. You can switch flutter channels using the directions [here](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels) 

Hopefully this get's published in the next flutter release soon.

**Comment by joshmossas** [comment] 2022-08-15 20:20
@Decoder07 the flutter 3.0 branch that you linked is gone now. Is there are branch that we can keep using for development?

**Comment by Decoder07** [comment] 2022-08-16 09:02
Hi! @joshmossas there were many issues coming with flutter 3.0 thatswhy we have removed the branch for now.You can find the issues here :
https://www.100ms.live/docs/flutter/v2/guides/quickstart#add-sdk-dependencies

Because of this we recommend `flutter 2.10.x` series.
Do you have any particular dependency on `flutter 3.x.x` ?

**Comment by joshmossas** [comment] 2022-08-16 17:58
We're using `flutter_riverpod 1.x.x` which requires the Flutter SDK to be version `>= 3.0.0`. There were a number of syntax changes from `flutter_riverpod 0.x.x` to `1.0.0` so I would prefer not to go back to using a depreciated version of riverpod

**Comment by joshmossas** [comment] 2022-08-16 18:03
It looks like `riverpod 1.0.3` has the minimum sdk set to `2.14.0` so we can probably use that in the mean time.

**Comment by Decoder07** [comment] 2022-08-16 18:12
Cool, because the fixes for platform views from flutter are still in beta. So, they can't be used for production.

**Comment by stuartmorgan** [comment] 2022-08-17 15:44
@Decoder07 We've had a report that this plugin still doesn't work in the current `beta`, which contains the change that was expected to resolve the layering issue. I've attempted to investigate, but the example app here doesn't build out of the box.

Would it be possible for you to follow up in https://github.com/flutter/flutter/issues/109689 to provide a minimal reproduction case?

**Comment by Decoder07** [comment] 2022-08-18 05:21
Hi @stuartmorgan,Thanks for looking into the issue.I will be providing a minimal app in sometime to reproduce the issue.

**Comment by stuartmorgan** [comment] 2022-08-18 14:25
The report that it didn't work in `beta` appears to have been a testing mistake by the reporter, so it looks like the layering issue is fixed there. If anyone has a case that reproduces it in `beta` or `master`, please follow up with details in https://github.com/flutter/flutter/issues/109689.

**Comment by Decoder07** [comment] 2022-08-18 16:53
Thanks @stuartmorgan
@rlee1990 @joshmossas closing the issue.

If you have face any other problems please create a new issue.

**Closed by Decoder07** 2022-08-18 16:53 UTC
